### ISSUE TITLE
Evaluate downstream on new dataset fail

### ISSUE THREAD

**Issue by AchilleSou** [s3prl/s3prl#123]
Hello team ! 

I pre-trained Mockingjay on the commonVoice dataset and then fine-tuned it for downstream ASR task on Librispeech data (it's for a domain-adaptation study).
I want to test this model on commonVoice test split and, to do so, I tried to override the config arguments to link back to my commonVoice data root, bucket directory and test split (as Librispeech use test-clean and test-other) like so : 
```
python3 run_downstream.py -m evaluate -t "test" -e result/downstream/Mockingjay_cv_lib/states-78000.ckpt  --override "config.downstream_expert.datarc.bucket_file='data/commonvoice/len_for_bucket',,config.downstream_expert.datarc.libri_root='/raid/dataset/speech_rec/datasets/commonVoice/data_16000hz/',,config.downstream_expert.datarc.test=['test']"
```

This runs fine at the beginning but it gives the following error : 
```
/home/jupyter/.conda/envs/my-env-3.7/lib/python3.7/site-packages/torchaudio/backend/utils.py:54: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  '"sox" backend is being deprecated. '
[hubconf] can not import upstream.decoar.hubconf: No module named 'mxnet'... Pass.
[hubconf] can not import upstream.pase.hubconf: No module named 'pase'... Pass.
[Runner] - Resume from result/downstream/Mockingjay_cv_lib/states-78000.ckpt
[Override] - config.downstream_expert.datarc.bucket_file = data/commonvoice/len_for_bucket
[Override] - config.downstream_expert.datarc.libri_root = /raid/dataset/speech_rec/datasets/commonVoice/data_16000hz/
[Override] - config.downstream_expert.datarc.test = ['test']
[UpstreamExpert] - Using the default upstream expert config
/home/jupyter/.conda/envs/my-env-3.7/lib/python3.7/site-packages/torchaudio/compliance/kaldi.py:574: UserWarning: The function torch.rfft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.fft or torch.fft.rfft. (Triggered internally at  /pytorch/aten/src/ATen/native/SpectralOps.cpp:590.)
  fft = torch.rfft(strided_input, 1, normalized=False, onesided=True)
ASR dataset train: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6979/6979 [00:00<00:00, 7772.54it/s]
[Runner] - Loading downstream weights from the previous experiment
Traceback (most recent call last):
  File "run_downstream.py", line 193, in <module>
    main()
  File "run_downstream.py", line 188, in main
    runner = Runner(args, config)
  File "/workspace/Documents/speech_rec/s3prl/downstream/runner.py", line 37, in __init__
    self.downstream = self._get_downstream()
  File "/workspace/Documents/speech_rec/s3prl/downstream/runner.py", line 103, in _get_downstream
    downstream.load_state_dict(init_downstream)
  File "/home/jupyter/.conda/envs/my-env-3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DownstreamExpert:
        size mismatch for model.linear.weight: copying a param with shape torch.Size([32, 2048]) from checkpoint, the shape in current model is torch.Size([64, 2048]).
        size mismatch for model.linear.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
```
It don't see where the size mismatch could come from as I just change data related configurations...

I get the same error using this command : 
```
 python3 run_downstream.py -m evaluate -t "test" -i result/downstream/Mockingjay_cv_lib/states-78000.ckpt --config downstream/asr/config_cv.yaml --upstream mockingjay_local --upstream_ckpt result/pretrain/Mockingjay_cv/states-epoch-252.ckpt -d asr
```
```
/home/jupyter/.conda/envs/my-env-3.7/lib/python3.7/site-packages/torchaudio/backend/utils.py:54: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  '"sox" backend is being deprecated. '
[hubconf] can not import upstream.decoar.hubconf: No module named 'mxnet'... Pass.
[hubconf] can not import upstream.pase.hubconf: No module named 'pase'... Pass.
[Runner] - Start a new experiment
[UpstreamExpert] - Using the default upstream expert config
/home/jupyter/.conda/envs/my-env-3.7/lib/python3.7/site-packages/torchaudio/compliance/kaldi.py:574: UserWarning: The function torch.rfft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.fft or torch.fft.rfft. (Triggered internally at  /pytorch/aten/src/ATen/native/SpectralOps.cpp:590.)
  fft = torch.rfft(strided_input, 1, normalized=False, onesided=True)
ASR dataset train: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6979/6979 [00:00<00:00, 7757.37it/s]
[Runner] - Loading downstream weights from the previous experiment
Traceback (most recent call last):
  File "run_downstream.py", line 193, in <module>
    main()
  File "run_downstream.py", line 188, in main
    runner = Runner(args, config)
  File "/workspace/Documents/speech_rec/s3prl/downstream/runner.py", line 37, in __init__
    self.downstream = self._get_downstream()
  File "/workspace/Documents/speech_rec/s3prl/downstream/runner.py", line 103, in _get_downstream
    downstream.load_state_dict(init_downstream)
  File "/home/jupyter/.conda/envs/my-env-3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DownstreamExpert:
        size mismatch for model.linear.weight: copying a param with shape torch.Size([32, 2048]) from checkpoint, the shape in current model is torch.Size([64, 2048]).
        size mismatch for model.linear.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
```

**Comment by andi611** [comment]
Hi,
After some investigation, I think the error you have is caused by data-related issues:

I believe you are using the RNNs model, where the size mismatch error is triggered at this [line](https://github.com/s3prl/s3prl/blob/6531904e9621a778978b9cfef3ba9f582e56639a/downstream/asr/model.py#L115).
From the above line, the `output_size` is determined by `len(self.train_dataset.symbols)` [here](https://github.com/s3prl/s3prl/blob/6531904e9621a778978b9cfef3ba9f582e56639a/downstream/asr/expert.py#L90),
which you can then trace back to these [lines](https://github.com/s3prl/s3prl/blob/6531904e9621a778978b9cfef3ba9f582e56639a/downstream/asr/dataset.py#L79-L88) in the `dataset.py`.

You may want to check out the [dictionary.py](https://github.com/s3prl/s3prl/blob/master/downstream/asr/dictionary.py) file and verify why it is creating a different amount of symbols for your two datasets.

I hope this helps!
Andy
