### ISSUE TITLE
torchaudio error

### ISSUE THREAD

**Issue by jefflai108** [s3prl/s3prl#141]
I got an error related to torchaudio while running keyword spotting (no issue for ASR/phone recognition). Im wondering if others have encountered it before: 

Traceback (most recent call last):                                                                    | 0/1596 [00:00<?, ?it/s]
  File "run_downstream.py", line 195, in <module>
    main()
  File "run_downstream.py", line 191, in main
    eval(f'runner.{args.mode}')()
  File "/nobackup/users/clai24/lth-wav2vec/s3prl/downstream/runner.py", line 194, in train
    for batch_id, (wavs, *others) in enumerate(tqdm(dataloader, dynamic_ncols=True, desc='train', file=tqdm_file)):
  File "/nobackup/users/clai24/tools/anaconda3/envs/s3prl/lib/python3.7/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/nobackup/users/clai24/tools/anaconda3/envs/s3prl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/nobackup/users/clai24/tools/anaconda3/envs/s3prl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/nobackup/users/clai24/tools/anaconda3/envs/s3prl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/nobackup/users/clai24/tools/anaconda3/envs/s3prl/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/nobackup/users/clai24/tools/anaconda3/envs/s3prl/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/nobackup/users/clai24/tools/anaconda3/envs/s3prl/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/nobackup/users/clai24/tools/anaconda3/envs/s3prl/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/nobackup/users/clai24/lth-wav2vec/s3prl/downstream/speech_commands/dataset.py", line 79, in __getitem__
    wav, label = super().__getitem__(idx)
  File "/nobackup/users/clai24/lth-wav2vec/s3prl/downstream/speech_commands/dataset.py", line 35, in __getitem__
    wav, _ = apply_effects_file(str(audio_path), EFFECTS)
  File "/nobackup/users/clai24/lth-wav2vec/s3prl/audio/torchaudio/_internal/module_utils.py", line 35, in wrapped
    raise RuntimeError(f'{func.__module__}.{func.__name__} requires {req}')
RuntimeError: torchaudio.sox_effects.sox_effects.apply_effects_file requires module: torchaudio._torchaudio

**Comment by mthrok** [comment]
Hi @jefflai108 

Can you run `python -m torch.utils.collect_env` and report the output?

The error message means that `torchaudio` you are using does not have the C++ extension.
This happens either if you are on Windows (not seemingly) or cloned repo but not built the extension.

**Comment by jefflai108** [comment]
oh i see. I did not install torchaudio in my environment but simply clone its repo and added to my PYTHONPATH. Should i build torchaudio from source instead? 

(torchaudio package is not supported in the computer cluster im using so i can not do pip/conda install)

**Comment by jefflai108** [comment]
here's the env stats: 

[pip3] numpy==1.19.5
[pip3] torch==1.7.1
[pip3] torchtext==0.8.0a0+0f911ec
[pip3] torchvision==0.8.2
[conda] _pytorch_select           2.0                  cuda10.2_1    https://opence.mit.edu
[conda] cudatoolkit               10.2.89            681.g0f7a43a    https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda-early-access
[conda] numpy                     1.19.5           py37ha4ee695_1    conda-forge
[conda] pytorch                   1.7.1           cuda10.2_py37_3    https://opence.mit.edu
[conda] pytorch-base              1.7.1           cuda10.2_py37_9    https://opence.mit.edu
[conda] torchtext                 0.8.1                    py37_4    https://opence.mit.edu
[conda] torchvision-base          0.8.2           cuda10.2_py37_6    https://opence.mit.edu

**Comment by mthrok** [comment]
I see. In that case, please build and install `torchaudio` from the source.

The following link best describes how to build from the source.
https://github.com/pytorch/audio/blob/master/CONTRIBUTING.md#install-torchaudio

If you encounter a problem, feel free to open an issue in [`torchaudio repo`](https://github.com/pytorch/audio/issues).

**Comment by jefflai108** [comment]
hi @mthrok  thanks for the reply. 

Im having trouble actually with installing cmake: 

"ERROR: Could not build wheels for cmake which use PEP 517 and cannot be installed directly"

Do you know how to solve this error?

**Comment by mthrok** [comment]
@jefflai108 

I have not seen the error. It seems to be related to `pip` and Python, rather than `torchaudio`.
It's hard to say what's the right workaround without access to the actual environment.
You might want to contact the support desk of your system.

As a side note, since your PyTorch is 1.7.1, the latest version of `torchaudio` will not work. You need to checkout [`v0.7.2` tag](https://github.com/pytorch/audio/releases/tag/v0.7.2).

**Comment by jefflai108** [comment]
got it. thanks for the info!
