### ISSUE TITLE
ModuleNotFoundError: No module named 'optimizers'

### ISSUE THREAD

**Issue by myhrbeu** [s3prl/s3prl#150]
Using cache found in /root/.cache/torch/hub/s3prl_s3prl_master
################################################################################
################################################################################

/usr/local/lib/python3.7/dist-packages/torchaudio/backend/utils.py:54: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  '"sox" backend is being deprecated. '
/bin/sh: 1: sox: not found
SoX could not be found!

    If you do not have SoX, proceed here:
     - - - http://sox.sourceforge.net/ - - -

    If you do (or think that you should) have SoX, double-check your
    path variables.
    
[Downstream] can not import .sv_voxceleb1.expert: No module named 'utility'... Pass.
[Downstream] can not import .speech_commands.expert: No module named 'catalyst'... Pass.
2021-07-15 23:28:08.427024: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
[hubconf] can not import .upstream.pase.hubconf: No module named 'pase'... Pass.
Using cache found in /root/.cache/torch/hub/s3prl_cache/55805839eb58b56972be4a9994ca99c862d2572cfd74ae26c916e8ced5d45a7a
for https://www.dropbox.com/s/3wgynxmod77ha1z/states-1000000.ckpt?dl=0
[UpstreamExpert] - Using the default upstream expert config
Traceback (most recent call last):
  line 30, in __init__
    self.features = torch.hub.load('s3prl/s3prl', 'audio_albert')
  File "/usr/local/lib/python3.7/dist-packages/torch/hub.py", line 370, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/hub.py", line 399, in _load_local
    model = entry(*args, **kwargs)
  File "/root/.cache/torch/hub/s3prl_s3prl_master/s3prl/upstream/audio_albert/hubconf.py", line 48, in audio_albert
    return audio_albert_960hr(refresh=refresh, *args, **kwargs)
  File "/root/.cache/torch/hub/s3prl_s3prl_master/s3prl/upstream/audio_albert/hubconf.py", line 61, in audio_albert_960hr
    return audio_albert_logMelBase_T_share_AdamW_b32_1m_960hr_drop1(refresh=refresh, *args, **kwargs)
  File "/root/.cache/torch/hub/s3prl_s3prl_master/s3prl/upstream/audio_albert/hubconf.py", line 79, in audio_albert_logMelBase_T_share_AdamW_b32_1m_960hr_drop1
    return audio_albert_url(refresh=refresh, *args, **kwargs)
  File "/root/.cache/torch/hub/s3prl_s3prl_master/s3prl/upstream/audio_albert/hubconf.py", line 40, in audio_albert_url
    return audio_albert_local(_urls_to_filepaths(ckpt, refresh=refresh), *args, **kwargs)
  File "/root/.cache/torch/hub/s3prl_s3prl_master/s3prl/upstream/audio_albert/hubconf.py", line 23, in audio_albert_local
    return _UpstreamExpert(ckpt, *args, **kwargs)
  File "/root/.cache/torch/hub/s3prl_s3prl_master/s3prl/upstream/interfaces.py", line 29, in __call__
    instance = super().__call__(*args, **kwargs)
  File "/root/.cache/torch/hub/s3prl_s3prl_master/s3prl/upstream/mockingjay/expert.py", line 51, in __init__
    self.transformer = PretrainedTransformer(options, inp_dim=-1)
  File "/root/.cache/torch/hub/s3prl_s3prl_master/s3prl/upstream/mockingjay/builder.py", line 255, in __init__
    super(PretrainedTransformer, self).__init__(options, inp_dim, config, online_config, verbose)
  File "/root/.cache/torch/hub/s3prl_s3prl_master/s3prl/upstream/mockingjay/builder.py", line 45, in __init__
    self.all_states = torch.load(options["ckpt_file"], map_location='cpu')
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'optimizers'

Is there an update in AAlbert？I found there‘s an error in my code which is no error yesterday.
Thanks!

**Comment by myhrbeu** [comment]
!pip install fairseq
!pip install torchaudio

!pip3 install pickle5
import pickle5 as pickle

Does it because of this?

**Comment by myhrbeu** [comment]
Can I save AAlbert as a model locally?
And load it from local, only from the net for the first time.
There have been several model upgrades that failed the experiment to run normally. Can this method be solved?

**Comment by leo19941227** [comment]
Hi,

Can you provide the current commit and the command you are using?
This will be helpful for me to dive into and reproduce the issue.
Thanks!

**Comment by myhrbeu** [comment]
Hi,
I just use it like yesterday.
!git clone https://github.com/s3prl/s3prl
!pip install -r requirements.txt

And use aalbert like this:
init function:
self.features = torch.hub.load('s3prl/s3prl', 'audio_albert')
forward function:
 x = torch.stack(self.features(x)['hidden_states'])

There are no other operations.  
Thanks!

**Comment by leo19941227** [comment]
Hi,

Thanks for reporting.
I already reproduce this issue on colab.
Let me debug it a little bit.

**Comment by myhrbeu** [comment]
Thanks a lot!

**Comment by leo19941227** [comment]
Hey!
Really thanks for pointing our this issue.
Recently we are working on packaging this repo and I did not realize I broke the functionality of mockingay, tera and audio_albert.
I believe this issue is resolved by b3e00259e81a9afd837f35bfd31dfc4679423e0b
Feel free to re-open if this does not work for you :)
