### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED - ASR

### ISSUE THREAD

**Issue by Enescigdem** [s3prl/s3prl#171]
hi, I got this error message after about 10k steps while conducting ASR with TERA.What could I do for solution? 
> Traceback (most recent call last):
  File "run_downstream.py", line 195, in <module>
    main()
  File "run_downstream.py", line 191, in main
    eval(f'runner.{args.mode}')()
  File "/lib/python3.8/site-packages/s3prl/downstream/runner.py", line 213, in train
    loss = self.downstream.model(
  File "/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/lib/python3.8/site-packages/s3prl/downstream/asr/expert.py", line 247, in forward
    logits, log_probs_len = self.model(features, features_len)
  File "/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/lib/python3.8/site-packages/s3prl/downstream/asr/model.py", line 130, in forward
    x, x_len = rnn(x, x_len)
  File "/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/python3.8/site-packages/s3prl/downstream/asr/model.py", line 58, in forward
    output, _ = self.layer(input_x)
  File "/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 682, in forward
    result = _VF.lstm(input, batch_sizes, hx, self._flat_weights, self.bias,
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

@andi611

**Comment by andi611** [comment]
@leo19941227 do you know what might cause this error?

**Comment by jefflai108** [comment]
I remember this happens some time, that's why there's the "fault-tolerant training" option

**Comment by Enescigdem** [comment]
> I remember this happens some time, that's why there's the "fault-tolerant training" option

fault tolerant training is just  restart the training but data preprocess takes a lot for my case for every start.

**Comment by leo19941227** [comment]
Hi,

For me the error is typically occur along with OOM.
May I ask what is your GPU memory size?

**Comment by Enescigdem** [comment]
Hi, @leo19941227 
16 GB

**Comment by leo19941227** [comment]
Oh then I think this is not due to OOM.
What about your cuda & cudnn version?

**Comment by leo19941227** [comment]
and the GPU you are using.

**Comment by leo19941227** [comment]
If you would like a temporary workaround. Maybe you can also try the following first:

```
torch.backends.cudnn.enabled = False
```

**Comment by Enescigdem** [comment]
Hi again,
Tesla P100 and CUDA version 11.1.
I can not try this right now but i will try and keep you updated about this .
Thanks in advance

**Comment by leo19941227** [comment]
I add an option `--disable_cudnn` for disabling CUDNN. Since the issue is related to CUDA and CUDNN installation which is hard to reproduce at my side. I will first use `disabling CUDNN` as the solution. Please feel free to reopen the issue if you find another better solution :)
