### ISSUE TITLE
The layerdrop issue of wav2vec2 models must be documented/printed somewhere

### ISSUE THREAD

**Issue by leo19941227** [s3prl/s3prl#192]
This might be the most asked question when people trying to finetune wav2vec2/hubert/decoar2 with downstream tasks since the `-s hidden_states` and weigthed-sum is the default mode.

**Comment by Sreyan88** [comment]
Hi @leo19941227 ,

Yes I face a similar issue. When I try layer 100 or 11 for wav2vec2 it shows me:

```
Featurizer for <class 's3prl.upstream.wav2vec2.expert.UpstreamExpert'>] - feature_selection = hidden_state_10 is not supported for this upstream.,  3.16it/s]
[Featurizer for <class 's3prl.upstream.wav2vec2.expert.UpstreamExpert'>] - Supported options: ['default', 'hidden_states', 'last_hidden_state', 'hidden_state_0', 'hidden_state_1', 'hidden_state_2', 'hidden_state_3', 'hidden_state_4', 'hidden_state_5', 'hidden_state_6', 'hidden_state_7']
train:  62%|______________________________________________________________________                                           | 21/34 [00:06<00:03,  3.47it/s]
Traceback (most recent call last):
  File "run_downstream.py", line 195, in <module>
    main()
  File "run_downstream.py", line 191, in main
    eval(f'runner.{args.mode}')()
  File "/speech/srayan/icassp_toxic/s3prl/s3prl/downstream/runner.py", line 212, in train
    features = self.featurizer.model(wavs, features)
  File "/speech/srayan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/speech/srayan/icassp_toxic/s3prl/s3prl/upstream/interfaces.py", line 227, in forward
    feature = self._select_feature(paired_features)
  File "/speech/srayan/icassp_toxic/s3prl/s3prl/upstream/interfaces.py", line 207, in _select_feature
    raise ValueError
ValueError
overall:   0%|                                                                                                           | 4/20000 [00:06<8:32:58,  1.54s/it]
```

and when no layer selected it throws:
```
train:   3%|____                                                                                                              | 1/34 [00:01<00:48,  1.46s/it]
Traceback (most recent call last):                                                                                            | 1/34 [00:01<00:41,  1.24s/it]
  File "run_downstream.py", line 195, in <module>
    main()
  File "run_downstream.py", line 191, in main
    eval(f'runner.{args.mode}')()
  File "/speech/srayan/icassp_toxic/s3prl/s3prl/downstream/runner.py", line 212, in train
    features = self.featurizer.model(wavs, features)
  File "/speech/srayan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/speech/srayan/icassp_toxic/s3prl/s3prl/upstream/interfaces.py", line 229, in forward
    feature = self._weighted_sum(feature)
  File "/speech/srayan/icassp_toxic/s3prl/s3prl/upstream/interfaces.py", line 211, in _weighted_sum
    assert self.layer_num == len(feature), f"{self.layer_num} != {len(feature)}"
AssertionError: 13 != 12
overall:   0%|                                                                                                                     | 0/20000 [00:01<?, ?it/s]
```

Is there a specific reason for this?

**Comment by jasonppy** [comment]
I think if the fairseq's original code of wav2vec2 is used, this wouldn't be a problem if model is set to eval(), see https://github.com/pytorch/fairseq/blob/master/fairseq/models/wav2vec/wav2vec2.py#L890

When model is being fine-tuned, we can set `layerdrop` to be 0

**Comment by Sreyan88** [comment]
Hi @jasonppy ,

How do we set layerdrop to be 0 if I want to finetune wav2vec2 on a downstream task? Do I just directly hard-code it in the source installation of fairseq in my environment?

Thank You

**Comment by jasonppy** [comment]
> Hi @jasonppy ,
> 
> How do we set layerdrop to be 0 if I want to finetune wav2vec2 on a downstream task? Do I just directly hard-code it in the source installation of fairseq in my environment?
> 
> Thank You

Yes, I would do that
