### ISSUE TITLE
ASR downstream resume error

### ISSUE THREAD

**Issue by liu-x-p** [s3prl/s3prl#218]
Hi, I tried to use this toolkit for ASR test. And I set '-f' to finetune the upstream model, I found there to be some error when I resume from previous training.
The command I used is `python run_downstream.py -e result/downstream/tera100cf41_lamta0d1_2_noacc20k20kasrft/states-500.ckpt -m train`
the error report is
```
Traceback (most recent call last):
  File "run_downstream.py", line 218, in <module>
    main()
  File "run_downstream.py", line 213, in main
    runner = Runner(args, config)
  File "/home/lxpeng/anaconda3/envs/s3prlmaster/lib/python3.8/site-packages/s3prl-0.3.1-py3.8.egg/s3prl/downstream/runner.py", line 94, in __init__
    self.upstream = self._get_upstream()
  File "/home/lxpeng/anaconda3/envs/s3prlmaster/lib/python3.8/site-packages/s3prl-0.3.1-py3.8.egg/s3prl/downstream/runner.py", line 150, in _get_upstream
    return self._init_model(
  File "/home/lxpeng/anaconda3/envs/s3prlmaster/lib/python3.8/site-packages/s3prl-0.3.1-py3.8.egg/s3prl/downstream/runner.py", line 111, in _init_model
    self._load_weight(model, name)
  File "/home/lxpeng/anaconda3/envs/s3prlmaster/lib/python3.8/site-packages/s3prl-0.3.1-py3.8.egg/s3prl/downstream/runner.py", line 104, in _load_weight
    model.load_state_dict(init_weight)
  File "/home/lxpeng/anaconda3/envs/s3prlmaster/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UpstreamExpert:
	size mismatch for transformer.extracter._melscale.fb: copying a param with shape torch.Size([201, 80]) from checkpoint, the shape in current model is torch.Size([0]). 
```

**Comment by leo19941227** [comment]
Hi @liu-x-p !

Thanks for pointing out!
I have fixed this.
