### ISSUE TITLE
Error: a2a-vc-vctk training crash with list index out of range

### ISSUE THREAD

**Issue by tarepan** [s3prl/s3prl#262]
## Summary
a2a-vc-vctk training crash with default setup.  
Error message says that there is list index out of range error in training loop.  
It seems to be caused by wrong default config, so I made PR.

## Config
master 3a90635e2ff546f2023813bf4b9ebaa576425023 with patch #261  

## Situation
Execute training of a2a-vc-vctk as in the [README](https://github.com/s3prl/s3prl/blob/master/s3prl/downstream/a2a-vc-vctk/README.md).  
When `./downstream/a2a-vc-vctk/vc_train.sh` run, it normally execute `train`, `dev` and `Saving` steps.  
Just after going into `test` step, the training crash with error.  

## Error
```
Saving files: 100% 539/540 [09:16<00:01,  1.18s/it]
Saving files: 100% 540/540 [09:16<00:00,  1.03s/it]
dev loss: 3.542290
test:   0% 0/80 [00:00<?, ?it/s]
train:   0% 0/7167 [11:56<?, ?it/s]
Traceback (most recent call last):
  File "run_downstream.py", line 219, in <module>
    main()
  File "run_downstream.py", line 215, in main
    eval(f'runner.{args.mode}')()
  File "/content/s3prl/s3prl/downstream/runner.py", line 362, in train
    save_names += self.evaluate(split, logger, global_step)
  File "/content/s3prl/s3prl/downstream/runner.py", line 443, in evaluate
    for batch_id, (wavs, *others) in enumerate(tqdm(dataloader, dynamic_ncols=True, desc=split, total=evaluate_steps)):
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/s3prl/s3prl/downstream/a2a-vc-vctk/dataset.py", line 164, in __getitem__
    ref_spk_name = os.path.basename(spk_emb_paths[0]).split("_")[0]
IndexError: list index out of range
```

## Expected Cause
The error occurs here.  
https://github.com/s3prl/s3prl/blob/9798ce4f492b718b2aa42dc7d2516f2a296a153b/s3prl/downstream/a2a-vc-vctk/dataset.py#L163-L164

When I debug `spk_emb_paths`, it is `[]` (it should be the target path).  

I checked the generated `./data/lists/eval_10sample_list.txt`,  
```
./downstream/a2o-vc-vcc2020/data/vcc2020/SEF1/E30001.wav
./downstream/a2o-vc-vcc2020/data/vcc2020/SEF1/E30002.wav
...
```
These is only a source utterance address, and no target utterance addresses.  
It means that pair generation or its arguments are wrong.  

Finally I found that `eval_data_root` config is wrong.  
It points `"./downstream/a2o-vc-vcc2020/data/vcc2020"`, but there is no file in the address in a2a-vc-vctk setup.  

## How to Fix
Fix the address config.  

I made pull request (sorry, I attempted to make **draft** PR, but made normal PR...).  
It will totally fix the problem.  
Could you review it?  

## Others
It seems that @unilight is good as reviewer (original code comitter).

**Comment by unilight** [comment]
@tarepan, thanks! One little request: can you make #260 and #263 into one PR?

**Comment by tarepan** [comment]
In my opinion, these two are different bugs.  
So keep them separating seems to be simple and good for tracking.  

Or should I follow your ways? (It is just tiny problem, I am grad to make them one PR)

**Comment by unilight** [comment]
Oh, it's actually okay. Let's keep it the current way then!
