### ISSUE TITLE
Loading hubert model error

### ISSUE THREAD

**Issue by adonisues** [s3prl/s3prl#353]
Hello

When I excute distiller example, I met error message below.
Can I get some help with this issue?
I think it's a problem with the import module.

`python3 run_pretrain.py -u distiller -g pretrain/distiller/config_model.yaml -n mytest`

[UpstreamPretrainExpert] - Using upstream config from: pretrain/distiller/config_model.yaml
[Dataset] - Sampling random segments for training, sample length: 250000
[Dataset] - Training data from these sets: ['train-clean-100', 'train-clean-360', 'train-other-500']
[Dataset] - Number of individual training instances: 281241
[UpstreamPretrainExpert] - Initializing model...
[DistillerModel] - Expands the output dimension by 2 times
[DistillerModel] - Pred layers: [4, 12]
[TransformerEncoder] - Attention type = original
[DistillerModel] - Out layer type: expand-last
[DistillerModel] - Inter dim = 768
Using cache found in /root/.cache/torch/hub/s3prl_s3prl_master
Traceback (most recent call last):
  File "run_pretrain.py", line 156, in <module>
    main()
  File "run_pretrain.py", line 150, in main
    runner = Runner(args, config)
  File "/local1/sshwang/trunk/distillation/s3prl/s3prl/pretrain/runner.py", line 44, in __init__
    self.upstream = self._get_upstream()
  File "/local1/sshwang/trunk/distillation/s3prl/s3prl/pretrain/runner.py", line 56, in _get_upstream
    self.args.multi_gpu).to(self.args.device)
  File "/local1/sshwang/trunk/distillation/s3prl/s3prl/pretrain/distiller/pretrain_expert.py", line 57, in __init__
    model_config, edict(self.upstream_config["teacher"])
  File "/local1/sshwang/trunk/distillation/s3prl/s3prl/pretrain/distiller/pretrain_expert.py", line 188, in __init__
    teacher = torch.hub.load("s3prl/s3prl", teacher_config.model)
  File "/local1/sshwang/trunk/distillation/venv/lib/python3.6/site-packages/torch/hub.py", line 399, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/local1/sshwang/trunk/distillation/venv/lib/python3.6/site-packages/torch/hub.py", line 425, in _load_local
    hub_module = import_module(MODULE_HUBCONF, hubconf_path)
  File "/local1/sshwang/trunk/distillation/venv/lib/python3.6/site-packages/torch/hub.py", line 76, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.cache/torch/hub/s3prl_s3prl_master/hubconf.py", line 1, in <module>
    from s3prl.hub import *
  File "/local1/sshwang/trunk/distillation/s3prl/s3prl/hub.py", line 30, in <module>
    _get_hubconf_entries()
  File "/local1/sshwang/trunk/distillation/s3prl/s3prl/hub.py", line 14, in _get_hubconf_entries
    _module = importlib.import_module(_module_name, package=__package__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/local1/sshwang/trunk/distillation/s3prl/s3prl/upstream/__init__.py", line 1, in <module>
    from . import experts
  File "/local1/sshwang/trunk/distillation/s3prl/s3prl/upstream/experts.py", line 24, in <module>
    _get_experts()
  File "/local1/sshwang/trunk/distillation/s3prl/s3prl/upstream/experts.py", line 11, in _get_experts
    _module = importlib.import_module(_module_name, package=__package__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/local1/sshwang/trunk/distillation/s3prl/s3prl/upstream/data2vec/expert.py", line 13, in <module>
    from . import model
  File "/local1/sshwang/trunk/distillation/s3prl/s3prl/upstream/data2vec/model.py", line 94, in <module>
    class Data2VecAudioModel(BaseFairseqModel):
  File "/local1/sshwang/trunk/distillation/venv/lib/python3.6/site-packages/fairseq/models/__init__.py", line 131, in register_model_cls
    raise ValueError("Cannot register duplicate model ({})".format(name))
ValueError: Cannot register duplicate model (data2vec_audio)

It seems to be loaded with the Python command line command.

![image](https://user-images.githubusercontent.com/14052287/172672537-140481a2-673a-475c-9f17-6c196007d4a3.png)

**Comment by adonisues** [comment]
If I delete the upstream/data2vec folder, it works fine.
Thank you

**Comment by leo19941227** [comment]
Hi, this is because data2vec uses new modules in fairseq. Hence you will need to reinstall s3prl to get the proper version of newer fairseq.
