### ISSUE TITLE
Problem in the ASR task. 

### ISSUE THREAD

**Issue by raotnameh** [s3prl/s3prl#355]
Traceback (most recent call last):
  File "/data/part4/s3prl/s3prl/downstream/runner.py", line 272, in train
    dataloader = self.downstream.model.get_dataloader(train_split, epoch=epoch)
TypeError: get_dataloader() got an unexpected keyword argument 'epoch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/part4/s3prl/s3prl/run_downstream.py", line 223, in <module>
    main()
  File "/data/part4/s3prl/s3prl/run_downstream.py", line 219, in main
    eval(f'runner.{args.mode}')()
  File "/data/part4/s3prl/s3prl/downstream/runner.py", line 275, in train
    dataloader = self.downstream.model.get_dataloader(train_split)
  File "/data/part4/s3prl/s3prl/downstream/asr/expert.py", line 122, in get_dataloader
    setattr(self, f'{split}_dataset', SequenceDataset(split, batch_size, self.dictionary, **self.datarc))
  File "/data/part4/s3prl/s3prl/downstream/asr/dataset.py", line 69, in __init__
    Y = self._load_transcript(X)
  File "/data/part4/s3prl/s3prl/downstream/asr/dataset.py", line 134, in _load_transcript
    assert os.path.exists(path)
AssertionError
overall:   0%|                                                               | 0/200000 [00:00<?, ?it/s]

**Comment by leo19941227** [comment]
Hi,

Do you still encounter this issue? I think it might be related to some path for the dataset is not correctly set.

**Comment by raotnameh** [comment]
Hi, 

Not anymore, Exactly it was because of PATH.
