### ISSUE TITLE
KeyError: 'unix_user' when pip install -e ./

### ISSUE THREAD

**Issue by tserdar** [s3prl/s3prl#381]
I cannot seem to install the repository. The output from the install is as follows:

```
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Obtaining file:///data/speech/speech_recognition/speaker_identification/s3prl
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch!=1.10.0,>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from s3prl==0.3.4) (1.11.0+cu115)
Requirement already satisfied: torchaudio>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from s3prl==0.3.4) (0.11.0+cu115)
Requirement already satisfied: torchvision>=0.8.0 in /usr/local/lib/python3.10/dist-packages (from s3prl==0.3.4) (0.12.0+cu115)
Requirement already satisfied: joblib>=0.12.4 in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (1.1.0)
Requirement already satisfied: librosa>=0.7.2 in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (0.9.1)
Requirement already satisfied: scipy>=1.5.4 in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (1.8.0)
Requirement already satisfied: scikit-learn>=0.23.2 in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (1.1.0)
Requirement already satisfied: PyYAML>=5.4 in /usr/lib/python3/dist-packages (from s3prl==0.3.4) (5.4.1)
Requirement already satisfied: tqdm>=4.56.0 in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (4.64.0)
Requirement already satisfied: numpy>=1.21 in /usr/local/lib/python3.10/dist-packages (from s3prl==0.3.4) (1.22.3)
Requirement already satisfied: pandas>=1.1.5 in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (1.4.2)
Requirement already satisfied: tensorboardX<2.3,>=1.9 in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (2.2)
Requirement already satisfied: matplotlib>=3.3.4 in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (3.5.2)
Requirement already satisfied: Pillow>=6.2.2 in /usr/lib/python3/dist-packages (from s3prl==0.3.4) (9.0.1)
Requirement already satisfied: numba>=0.48 in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (0.55.2)
Requirement already satisfied: gdown>=3.12.2 in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (4.4.0)
Requirement already satisfied: cython>=0.29.21 in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (0.29.30)
Requirement already satisfied: packaging>=20.9 in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (21.3)
Requirement already satisfied: transformers<5.0,>=4.10.0 in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (4.20.1)
Requirement already satisfied: dtw-python==1.1.6 in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (1.1.6)
Requirement already satisfied: asteroid==0.4.4 in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (0.4.4)
Requirement already satisfied: sacrebleu>=2.0.0 in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (2.1.0)
Requirement already satisfied: kaldi_io in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (0.9.4)
Requirement already satisfied: h5py in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (3.7.0)
Requirement already satisfied: sox in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (1.4.1)
Requirement already satisfied: tabulate in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (0.8.9)
Requirement already satisfied: intervaltree in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (3.1.0)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from s3prl==0.3.4) (4.8.0)
Requirement already satisfied: soundfile in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (0.10.3.post1)
Requirement already satisfied: pysndfx in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (0.3.6)
Requirement already satisfied: nltk in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (3.7)
Requirement already satisfied: normalise in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (0.1.8)
Requirement already satisfied: editdistance in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (0.6.0)
Requirement already satisfied: easydict in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (1.9)
Requirement already satisfied: catalyst in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (22.4)
Requirement already satisfied: sentencepiece in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (0.1.95)
Requirement already satisfied: huggingface_hub>=0.2.1 in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (0.7.0)
Requirement already satisfied: mutagen in /home/computer/.local/lib/python3.10/site-packages (from s3prl==0.3.4) (1.45.1)
Requirement already satisfied: julius in /home/computer/.local/lib/python3.10/site-packages (from asteroid==0.4.4->s3prl==0.3.4) (0.2.6)
Requirement already satisfied: torch-optimizer>=0.0.1a12 in /home/computer/.local/lib/python3.10/site-packages (from asteroid==0.4.4->s3prl==0.3.4) (0.3.0)
Requirement already satisfied: asteroid-filterbanks>=0.2.4 in /home/computer/.local/lib/python3.10/site-packages (from asteroid==0.4.4->s3prl==0.3.4) (0.4.0)
Requirement already satisfied: torch-stoi>=0.1.2 in /home/computer/.local/lib/python3.10/site-packages (from asteroid==0.4.4->s3prl==0.3.4) (0.1.2)
Requirement already satisfied: pytorch-lightning>=1.0.1 in /home/computer/.local/lib/python3.10/site-packages (from asteroid==0.4.4->s3prl==0.3.4) (1.6.4)
Requirement already satisfied: pb-bss-eval>=0.0.2 in /home/computer/.local/lib/python3.10/site-packages (from asteroid==0.4.4->s3prl==0.3.4) (0.0.2)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from gdown>=3.12.2->s3prl==0.3.4) (4.10.0)
Requirement already satisfied: requests[socks] in /usr/lib/python3/dist-packages (from gdown>=3.12.2->s3prl==0.3.4) (2.25.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from gdown>=3.12.2->s3prl==0.3.4) (1.16.0)
Requirement already satisfied: filelock in /home/computer/.local/lib/python3.10/site-packages (from gdown>=3.12.2->s3prl==0.3.4) (3.7.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub>=0.2.1->s3prl==0.3.4) (4.2.0)
Requirement already satisfied: audioread>=2.1.5 in /home/computer/.local/lib/python3.10/site-packages (from librosa>=0.7.2->s3prl==0.3.4) (2.1.9)
Requirement already satisfied: resampy>=0.2.2 in /home/computer/.local/lib/python3.10/site-packages (from librosa>=0.7.2->s3prl==0.3.4) (0.2.2)
Requirement already satisfied: pooch>=1.0 in /home/computer/.local/lib/python3.10/site-packages (from librosa>=0.7.2->s3prl==0.3.4) (1.6.0)
Requirement already satisfied: decorator>=4.0.10 in /usr/lib/python3/dist-packages (from librosa>=0.7.2->s3prl==0.3.4) (4.4.2)
Requirement already satisfied: cycler>=0.10 in /home/computer/.local/lib/python3.10/site-packages (from matplotlib>=3.3.4->s3prl==0.3.4) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/computer/.local/lib/python3.10/site-packages (from matplotlib>=3.3.4->s3prl==0.3.4) (1.4.2)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/lib/python3/dist-packages (from matplotlib>=3.3.4->s3prl==0.3.4) (2.4.7)
Requirement already satisfied: fonttools>=4.22.0 in /home/computer/.local/lib/python3.10/site-packages (from matplotlib>=3.3.4->s3prl==0.3.4) (4.33.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/lib/python3/dist-packages (from matplotlib>=3.3.4->s3prl==0.3.4) (2.8.1)
Requirement already satisfied: setuptools in /home/computer/.local/lib/python3.10/site-packages (from numba>=0.48->s3prl==0.3.4) (59.5.0)
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in /home/computer/.local/lib/python3.10/site-packages (from numba>=0.48->s3prl==0.3.4) (0.38.1)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas>=1.1.5->s3prl==0.3.4) (2022.1)
Requirement already satisfied: regex in /home/computer/.local/lib/python3.10/site-packages (from sacrebleu>=2.0.0->s3prl==0.3.4) (2022.4.24)
Requirement already satisfied: portalocker in /home/computer/.local/lib/python3.10/site-packages (from sacrebleu>=2.0.0->s3prl==0.3.4) (2.4.0)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from sacrebleu>=2.0.0->s3prl==0.3.4) (0.4.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/computer/.local/lib/python3.10/site-packages (from scikit-learn>=0.23.2->s3prl==0.3.4) (3.1.0)
Requirement already satisfied: cffi>=1.0 in /home/computer/.local/lib/python3.10/site-packages (from soundfile->s3prl==0.3.4) (1.15.0)
Requirement already satisfied: protobuf>=3.8.0 in /home/computer/.local/lib/python3.10/site-packages (from tensorboardX<2.3,>=1.9->s3prl==0.3.4) (3.19.4)
Requirement already satisfied: tokenizers!=0.11.3,<0.13,>=0.11.1 in /home/computer/.local/lib/python3.10/site-packages (from transformers<5.0,>=4.10.0->s3prl==0.3.4) (0.11.6)
Requirement already satisfied: hydra-slayer>=0.4.0 in /home/computer/.local/lib/python3.10/site-packages (from catalyst->s3prl==0.3.4) (0.4.0)
Requirement already satisfied: accelerate>=0.5.1 in /home/computer/.local/lib/python3.10/site-packages (from catalyst->s3prl==0.3.4) (0.11.0)
Requirement already satisfied: sortedcontainers<3.0,>=2.0 in /home/computer/.local/lib/python3.10/site-packages (from intervaltree->s3prl==0.3.4) (2.4.0)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from nltk->s3prl==0.3.4) (8.0.3)
Requirement already satisfied: roman in /home/computer/.local/lib/python3.10/site-packages (from normalise->s3prl==0.3.4) (3.3)
Requirement already satisfied: psutil in /home/computer/.local/lib/python3.10/site-packages (from accelerate>=0.5.1->catalyst->s3prl==0.3.4) (5.9.1)
Requirement already satisfied: pycparser in /home/computer/.local/lib/python3.10/site-packages (from cffi>=1.0->soundfile->s3prl==0.3.4) (2.21)
Requirement already satisfied: einops in /home/computer/.local/lib/python3.10/site-packages (from pb-bss-eval>=0.0.2->asteroid==0.4.4->s3prl==0.3.4) (0.4.1)
Requirement already satisfied: cached-property in /home/computer/.local/lib/python3.10/site-packages (from pb-bss-eval>=0.0.2->asteroid==0.4.4->s3prl==0.3.4) (1.5.2)
Requirement already satisfied: pesq in /home/computer/.local/lib/python3.10/site-packages (from pb-bss-eval>=0.0.2->asteroid==0.4.4->s3prl==0.3.4) (0.0.4)
Requirement already satisfied: mir-eval in /home/computer/.local/lib/python3.10/site-packages (from pb-bss-eval>=0.0.2->asteroid==0.4.4->s3prl==0.3.4) (0.7)
Requirement already satisfied: pystoi in /home/computer/.local/lib/python3.10/site-packages (from pb-bss-eval>=0.0.2->asteroid==0.4.4->s3prl==0.3.4) (0.3.3)
Requirement already satisfied: appdirs>=1.3.0 in /usr/lib/python3/dist-packages (from pooch>=1.0->librosa>=0.7.2->s3prl==0.3.4) (1.4.4)
Requirement already satisfied: pyDeprecate>=0.3.1 in /home/computer/.local/lib/python3.10/site-packages (from pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (0.3.2)
Requirement already satisfied: fsspec[http]!=2021.06.0,>=2021.05.0 in /home/computer/.local/lib/python3.10/site-packages (from pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (2022.5.0)
Requirement already satisfied: tensorboard>=2.2.0 in /home/computer/.local/lib/python3.10/site-packages (from pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (2.9.0)
Requirement already satisfied: torchmetrics>=0.4.1 in /home/computer/.local/lib/python3.10/site-packages (from pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (0.9.1)
Requirement already satisfied: pytorch-ranger>=0.1.1 in /home/computer/.local/lib/python3.10/site-packages (from torch-optimizer>=0.0.1a12->asteroid==0.4.4->s3prl==0.3.4) (0.1.1)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /home/computer/.local/lib/python3.10/site-packages (from requests[socks]->gdown>=3.12.2->s3prl==0.3.4) (1.7.1)
Requirement already satisfied: aiohttp in /home/computer/.local/lib/python3.10/site-packages (from fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (3.8.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in /home/computer/.local/lib/python3.10/site-packages (from tensorboard>=2.2.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (2.6.6)
Requirement already satisfied: markdown>=2.6.8 in /home/computer/.local/lib/python3.10/site-packages (from tensorboard>=2.2.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (3.3.7)
Requirement already satisfied: wheel>=0.26 in /usr/lib/python3/dist-packages (from tensorboard>=2.2.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (0.37.1)
Requirement already satisfied: grpcio>=1.24.3 in /home/computer/.local/lib/python3.10/site-packages (from tensorboard>=2.2.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (1.46.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /home/computer/.local/lib/python3.10/site-packages (from tensorboard>=2.2.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (0.6.1)
Requirement already satisfied: absl-py>=0.4 in /home/computer/.local/lib/python3.10/site-packages (from tensorboard>=2.2.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (1.1.0)
Requirement already satisfied: werkzeug>=1.0.1 in /home/computer/.local/lib/python3.10/site-packages (from tensorboard>=2.2.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (2.1.2)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/computer/.local/lib/python3.10/site-packages (from tensorboard>=2.2.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (1.8.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/computer/.local/lib/python3.10/site-packages (from tensorboard>=2.2.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (0.4.6)
Requirement already satisfied: future in /home/computer/.local/lib/python3.10/site-packages (from mir-eval->pb-bss-eval>=0.0.2->asteroid==0.4.4->s3prl==0.3.4) (0.18.2)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/computer/.local/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (5.1.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/computer/.local/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/computer/.local/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (4.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/computer/.local/lib/python3.10/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.2.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (1.3.1)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /home/computer/.local/lib/python3.10/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (2.0.12)
Requirement already satisfied: attrs>=17.3.0 in /usr/lib/python3/dist-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (21.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/computer/.local/lib/python3.10/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (6.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in /home/computer/.local/lib/python3.10/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (1.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/computer/.local/lib/python3.10/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (1.3.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /home/computer/.local/lib/python3.10/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/computer/.local/lib/python3.10/site-packages (from aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (1.7.2)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/computer/.local/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard>=2.2.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.2.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (3.2.0)
Requirement already satisfied: idna>=2.0 in /home/computer/.local/lib/python3.10/site-packages (from yarl<2.0,>=1.0->aiohttp->fsspec[http]!=2021.06.0,>=2021.05.0->pytorch-lightning>=1.0.1->asteroid==0.4.4->s3prl==0.3.4) (2.10)
Installing collected packages: s3prl
  Running setup.py develop for s3prl
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [29 lines of output]
        running develop
        /home/computer/.local/lib/python3.10/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/data/speech/speech_recognition/speaker_identification/s3prl/setup.py", line 87, in <module>
            setup(
          File "/home/computer/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
            return distutils.core.setup(**attrs)
          File "/home/computer/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
            return run_commands(dist)
          File "/home/computer/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
            dist.run_commands()
          File "/home/computer/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
            self.run_command(cmd)
          File "/home/computer/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 985, in run_command
            cmd_obj.ensure_finalized()
          File "/home/computer/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
            self.finalize_options()
          File "/home/computer/.local/lib/python3.10/site-packages/setuptools/command/develop.py", line 52, in finalize_options
            easy_install.finalize_options(self)
          File "/home/computer/.local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 263, in finalize_options
            self._fix_install_dir_for_user_site()
          File "/home/computer/.local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 375, in _fix_install_dir_for_user_site
            self.select_scheme(scheme_name)
          File "/home/computer/.local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 716, in select_scheme
            scheme = INSTALL_SCHEMES[name]
        KeyError: 'unix_user'
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [29 lines of output]
    running develop
    /home/computer/.local/lib/python3.10/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/data/speech/speech_recognition/speaker_identification/s3prl/setup.py", line 87, in <module>
        setup(
      File "/home/computer/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/computer/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/home/computer/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/home/computer/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/home/computer/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 985, in run_command
        cmd_obj.ensure_finalized()
      File "/home/computer/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/home/computer/.local/lib/python3.10/site-packages/setuptools/command/develop.py", line 52, in finalize_options
        easy_install.finalize_options(self)
      File "/home/computer/.local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 263, in finalize_options
        self._fix_install_dir_for_user_site()
      File "/home/computer/.local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 375, in _fix_install_dir_for_user_site
        self.select_scheme(scheme_name)
      File "/home/computer/.local/lib/python3.10/site-packages/setuptools/command/easy_install.py", line 716, in select_scheme
        scheme = INSTALL_SCHEMES[name]
    KeyError: 'unix_user'
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by dlion168** [comment]
Encounter the same issue, this happens when I try to run 
`pip install -e ./` and `pip install s3prl[all]`
