### ISSUE TITLE
There are tasks that ESPNET does with S3PRL that fail

### ISSUE THREAD

**Issue by abcdbosh** [s3prl/s3prl#402]
File "/media/shiyanshi/E/espnet/espnet2/asr/frontend/s3prl.py", line 26, in __init__
    import s3prl.nn
ModuleNotFoundError: No module named 's3prl.nn'
Error: S3PRL is not properly installed.
Please install S3PRL: cd ${MAIN_ROOT}/tools && make s3prl.done

But S3PRL is successfully installed and can also be imported successfully in the terminal，How do I fix it?

**Comment by leo19941227** [comment]
Hi, can you try to `pip show s3prl` to see its version?
Please upgrade to the latest version `v0.4.4`

**Comment by abcdbosh** [comment]
Already the latest version 0.4.4：

**Comment by leo19941227** [comment]
Are you sure the environment the ESPNET recipe evokes is the same as the one you use when trying in the terminal?
Like, they are the same conda environment right? I remember ESPNET is using `activate_python.sh` to assign the conda env.

**Comment by abcdbosh** [comment]
Yes, I've tried it, but it still doesn't work.

**Comment by leo19941227** [comment]
Oh, I guess I know the reason.
You are using older version of ESPNet.
Could you try to upgrade ESPNet repo to be newer than this commit?

https://github.com/espnet/espnet/commit/0a62508814792bc4afb7991f152fa0ea75c7c863

**Comment by abcdbosh** [comment]
Okay, the power in the laboratory has been cut off... I'll get back to you when I try tomorrow morning. Thank you.

**Comment by abcdbosh** [comment]
espnet was updated, but new issues appeared in stage10 in espnet2
Traceback (most recent call last):
  File "/home/shiyanshi/anaconda3/envs/espnet1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/shiyanshi/anaconda3/envs/espnet1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/shiyanshi/F/2021_s/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/media/shiyanshi/F/2021_s/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/media/shiyanshi/F/2021_s/espnet/espnet2/tasks/abs_task.py", line 1019, in main
    cls.main_worker(args)
  File "/media/shiyanshi/F/2021_s/espnet/espnet2/tasks/abs_task.py", line 1121, in main_worker
    model = cls.build_model(args=args)
  File "/media/shiyanshi/F/2021_s/espnet/espnet2/tasks/asr.py", line 417, in build_model
    frontend = frontend_class(**args.frontend_conf)
  File "/media/shiyanshi/F/2021_s/espnet/espnet2/asr/frontend/s3prl.py", line 46, in __init__
    upstream = S3PRLUpstream(
  File "/home/shiyanshi/anaconda3/envs/espnet1/lib/python3.9/site-packages/s3prl/nn/upstream.py", line 96, in __init__
    self.upstream = getattr(hub, name)(
  File "/home/shiyanshi/anaconda3/envs/espnet1/lib/python3.9/site-packages/s3prl/upstream/hubert/hubconf.py", line 33, in hubert_local
    return hubert_custom(*args, **kwargs)
  File "/home/shiyanshi/anaconda3/envs/espnet1/lib/python3.9/site-packages/s3prl/upstream/hubert/hubconf.py", line 22, in hubert_custom
    if ckpt.startswith("http"):
AttributeError: 'NoneType' object has no attribute 'startswith'
# Accounting: time=6 threads=1
# Ended (code 1) at Fri Sep 30 22:05:12 CST 2022, elapsed time 6 seconds

**Comment by abcdbosh** [comment]
espnet was updated, but new issues appeared in stage10 in espnet2：

Traceback (most recent call last):
  File "/home/shiyanshi/anaconda3/envs/espnet1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/shiyanshi/anaconda3/envs/espnet1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/media/shiyanshi/F/2021_s/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/media/shiyanshi/F/2021_s/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/media/shiyanshi/F/2021_s/espnet/espnet2/tasks/abs_task.py", line 1019, in main
    cls.main_worker(args)
  File "/media/shiyanshi/F/2021_s/espnet/espnet2/tasks/abs_task.py", line 1121, in main_worker
    model = cls.build_model(args=args)
  File "/media/shiyanshi/F/2021_s/espnet/espnet2/tasks/asr.py", line 417, in build_model
    frontend = frontend_class(**args.frontend_conf)
  File "/media/shiyanshi/F/2021_s/espnet/espnet2/asr/frontend/s3prl.py", line 46, in __init__
    upstream = S3PRLUpstream(
  File "/home/shiyanshi/anaconda3/envs/espnet1/lib/python3.9/site-packages/s3prl/nn/upstream.py", line 96, in __init__
    self.upstream = getattr(hub, name)(
  File "/home/shiyanshi/anaconda3/envs/espnet1/lib/python3.9/site-packages/s3prl/upstream/hubert/hubconf.py", line 33, in hubert_local
    return hubert_custom(*args, **kwargs)
  File "/home/shiyanshi/anaconda3/envs/espnet1/lib/python3.9/site-packages/s3prl/upstream/hubert/hubconf.py", line 22, in hubert_custom
    if ckpt.startswith("http"):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by leo19941227** [comment]
Do you set the config like this?

https://github.com/espnet/espnet/blob/14fcb2d42b2609f766ffaa7a79e9c921cd8398d9/egs2/librispeech/asr1/conf/tuning/train_asr_conformer7_hubert_ll60k_large.yaml#L18-L23

It seems the name you pass into the `s3prl frontend` is None

**Comment by abcdbosh** [comment]
My configuration is as follows:
# network architecture
# pretrained model related
freeze_param: [
"frontend.upstream"
]

frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: hubert_local
        upstream_model_config:
        upstream_ckpt: /media/shiyanshi/F/2021_s/chinese-hubert-base/chinese-hubert-base.pt
    download_dir: ./hub
    multilayer_feature: true

preencoder: linear
preencoder_conf:
    input_size: 768  # Note: If the upstream is changed, please change this value accordingly.
    output_size: 80

# encoder related
encoder: conformer
encoder_conf:
    output_size: 256    # dimension of attention
    attention_heads: 4
    linear_units: 2048  # the number of units of position-wise feed forward
    num_blocks: 12      # the number of encoder blocks
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d2 # encoder architecture type
    normalize_before: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    cnn_module_kernel: 15

**Comment by leo19941227** [comment]
Oh... I think usually we do not expect to use custom pre-trained model with this frontend. I expect that this checkpoint is pre-trained from fairseq right? Currently we do not support `hubert_local` to load checkpoint from fairseq since this will require to install fairseq, which is a dependency we are trying to remove. We will support to directly load the fairseq-pretrained checkpoint in the upcoming release. However, this is not supported right now.

**Comment by leo19941227** [comment]
However, if you want, you can try to convert your checkpoint with this script:

https://github.com/s3prl/s3prl/blob/main/s3prl/upstream/hubert/convert.py

and the converted checkpoint can be loaded with `hubert_local`

**Comment by abcdbosh** [comment]
thank you!

**Comment by abcdbosh** [comment]
I'm sorry, but since I'm just getting started, I have to disturb you, the converted output path is empty, and how to set the configuration file~    /qaq

**Comment by bofenghuang** [comment]
Hi @leo19941227, could we still load custom pretrained models from huggingface? In the old versions, I could easily do this by add entries in `wav2vec2_hug/hubconf.py` :). Thanks in advance!

**Comment by leo19941227** [comment]
Hi, oh I removed that entry since previously it is kind of a duplicate function to the fairseq version and the fairseq version is somehow faster. But I will consider adding it back, since I also notice that there are many new pre-trained wav2vec2/hubert weights released in the huggingface format, and adding this entry back is not just duplication of the fairseq version, but enabling much more pre-trained models. Thanks for brining this up!

**Comment by sendream** [comment]
> 但是，如果您愿意，您可以尝试使用以下脚本转换您的检查点：
> 
> https://github.com/s3prl/s3prl/blob/main/s3prl/upstream/hubert/convert.py
> 
> 并且可以加载转换后的检查点`hubert_local`

Hi, I had the same problem, I was using converted checkpoints and the problem was not resolved.

**Comment by sendream** [comment]
> However, if you want, you can try to convert your checkpoint with this script:
> 
> https://github.com/s3prl/s3prl/blob/main/s3prl/upstream/hubert/convert.py
> 
> and the converted checkpoint can be loaded with `hubert_local`

Hi, I had the same problem, I was using converted checkpoints and the problem was not resolved.

**Comment by leo19941227** [comment]
I believe this issue is improved in #443, so I am closing it for now.
Feel free to re-open it if it does not fit your need. Thanks!
