### ISSUE TITLE
No such file or directory while opening './4-gram.arpa.gz' KenLM

### ISSUE THREAD

**Issue by benam2** [s3prl/s3prl#416]
Hi @leo19941227, Could you please help with this error? Is there anything to consider while installing the KENLM?
I followed the link here for the installation [https://medium.com/tekraze/install-kenlm-binaries-on-ubuntu-language-model-inference-tool-33507000f33](url).
I have checked and this file exist in my system (I have placed it in the same root to make sure the problem is not with the path)

```
Traceback (most recent call last):
  File "run_downstream.py", line 206, in <module>
    main()
  File "run_downstream.py", line 201, in main
    runner = Runner(args, config)
  File "/home/ai-labs/Desktop/ASR/s3prl/s3prl/downstream/runner.py", line 52, in __init__
    self.downstream = self._get_downstream()
  File "/home/ai-labs/Desktop/ASR/s3prl/s3prl/downstream/runner.py", line 129, in _get_downstream
    model = Downstream(
  File "/home/ai-labs/Desktop/ASR/s3prl/s3prl/downstream/asr/expert.py", line 99, in __init__
    self.decoder = get_decoder(decoder_args, self.dictionary)
  File "/home/ai-labs/Desktop/ASR/s3prl/s3prl/downstream/asr/expert.py", line 36, in get_decoder
    return W2lKenLMDecoder(decoder_args, dictionary)
  File "/home/ai-labs/Desktop/ASR/s3prl/s3prl/downstream/asr/w2l_decoder.py", line 127, in __init__
    self.lm = KenLM('./4-gram.arpa.gz', self.word_dict)
RuntimeError: /home/ai-labs/Desktop/ASR/kenlm/util/file.cc:76 in int util::OpenReadOrThrow(const char*) threw ErrnoException because `-1 == (ret = open(name, 00))'.
No such file or directory while opening ./4-gram.arpa.gz

```

**Comment by leo19941227** [comment]
Hi,

Did you place the `4-gram.arga.gz` path (absolute path preferably) in the asr config?

**Comment by benam2** [comment]
@leo19941227 Yes, and this is what I have `kenlm_model: './language_model/4-gram.arpa.gz'` but to make sure this is not something related to not finding the file, I placed that file in the same folder the `asr` folder and then change the code to this: `self.lm = KenLM('./4-gram.arpa.gz', self.word_dict)` but I'm getting the same error. 
Thanks for taking the time to fix this issue.

**Comment by leo19941227** [comment]
Can you try to fill the config field with the absolute path?

**Comment by benam2** [comment]
@leo19941227 yesss it fixed it, any reason for that?

After that, I got this error

```
Traceback (most recent call last):
  File "run_downstream.py", line 206, in <module>
    main()
  File "run_downstream.py", line 202, in main
    eval(f'runner.{args.mode}')()
  File "/home/ai-labs/Desktop/ASR/s3prl/s3prl/downstream/runner.py", line 416, in inference
    assert filepath.is_file()
AssertionError
```

do you mind having your idea share what it is related. The error itself does not give any information.
Thanks a lot for the help :)

**Comment by leo19941227** [comment]
You should use `--mode evaluate` instead of `--mode inference`

**Comment by benam2** [comment]
@leo19941227 Im trying to do inference on one sample. Should I change the mode to `evaluate`?

Anyway I did that and I got this error:

```
Traceback (most recent call last):
  File "run_downstream.py", line 206, in <module>
    main()
  File "run_downstream.py", line 202, in main
    eval(f'runner.{args.mode}')()
  File "/home/ai-labs/Desktop/ASR/s3prl/s3prl/downstream/runner.py", line 371, in evaluate
    dataloader = self.downstream.model.get_dataloader(split)
  File "/home/ai-labs/Desktop/ASR/s3prl/s3prl/downstream/asr/expert.py", line 122, in get_dataloader
    setattr(self, f'{split}_dataset', SequenceDataset(split, batch_size, self.dictionary, **self.datarc))
  File "/home/ai-labs/Desktop/ASR/s3prl/s3prl/downstream/asr/dataset.py", line 45, in __init__
    self.split_sets = kwargs[split]
KeyError: 'test'
```
Is there any instruction I can follow?

**Comment by benam2** [comment]
@leo19941227 I was just checking the code and I think passing `evaluate` will evaluate the dataset we pass on that. even though in the code it says we have the option for `train` `evaluate` `inference` but in the readme it mentions this: `-m or --mode specifies the train/evaluate mode`. Its a little bit confusing.

I want. to pass a recording and get the transcription.  
Could you please help me with this? or share if there is any instruction that I have missed it. Thanks again for taking the time.

**Comment by benam2** [comment]
Thanks for your help @leo19941227
