### ISSUE TITLE
Error on using Byol-S

### ISSUE THREAD

**Issue by bagustris** [s3prl/s3prl#476]
# Bug report

**Describe the bug**
Byol-S (tried `byol_s_cvt` and `byol_s_resnetish34`) hits errors when used as upstream.

**To Reproduce**
First, I tried `byol_s_cvt` as follows:

```
(.env) bagus@m049:s3prl$ python3 run_downstream.py -m train -n emofilm-byol-s-cvt-128 -u byol_s_cvt -d emofilm
[Runner] - Start a new experiment
INFO:s3prl.util.download:Requesting URL: https://github.com/GasserElbanna/serab-byols/raw/main/checkpoints/cvt_s1-d1-e64_s2-d1-e256_s3-d1-e512_BYOLAs64x96-osandbyolaloss6373-e100-bs256-lr0003-rs42.pth
Downloading: https://github.com/GasserElbanna/serab-byols/raw/main/checkpoints/cvt_s1-d1-e64_s2-d1-e256_s3-d1-e512_BYOLAs64x96-osandbyolaloss6373-e100-bs256-lr0003-rs42.pth
Destination: /home/bagus/.cache/s3prl/download/8fe587803104d95526420ddb589762052a5182780ee400e93eadb8c4a1a8d41d.cvt_s1-d1-e64_s2-d1-e256_s3-d1-e512_BYOLAs64x96-osandbyolaloss6373-e100-bs256-lr0003-rs42.pth
100%|█████████████████████████████████████████████████████████████| 19.2M/19.2M [00:00<00:00, 111MB/s]
INFO:s3prl.util.download:Using URL's local file: /home/bagus/.cache/s3prl/download/8fe587803104d95526420ddb589762052a5182780ee400e93eadb8c4a1a8d41d.cvt_s1-d1-e64_s2-d1-e256_s3-d1-e512_BYOLAs64x96-osandbyolaloss6373-e100-bs256-lr0003-rs42.pth
Traceback (most recent call last):
  File "run_downstream.py", line 218, in <module>
    main()
  File "run_downstream.py", line 213, in main
    runner = Runner(args, config)
  File "/home/bagus/github/s3prl-ser/s3prl/downstream/runner.py", line 93, in __init__
    self.upstream = self._get_upstream()
  File "/home/bagus/github/s3prl-ser/s3prl/downstream/runner.py", line 149, in _get_upstream
    model = Upstream(
  File "/home/bagus/github/s3prl-ser/s3prl/upstream/byol_s/hubconf.py", line 21, in byol_s_cvt
    return _UpstreamExpert(**kwds)
TypeError: __init__() got an unexpected keyword argument 'model_config'
```

The error also appears on Byol S ResNet version.
```
(.env) bagus@m049:s3prl$ python3 run_downstream.py -m train -n emofilm-byol_s_resnetish34-128 -u byol_s_resnetish34 -d emofilm
[Runner] - Start a new experiment
INFO:s3prl.util.download:Requesting URL: https://github.com/GasserElbanna/serab-byols/raw/main/checkpoints/resnetish34_BYOLAs64x96-2105271915-e100-bs256-lr0003-rs42.pth
Downloading: https://github.com/GasserElbanna/serab-byols/raw/main/checkpoints/resnetish34_BYOLAs64x96-2105271915-e100-bs256-lr0003-rs42.pth
Destination: /home/bagus/.cache/s3prl/download/b1ba7c8535b821757435847b42f913e2e93ce1c33622b7b6908da9265ceece97.resnetish34_BYOLAs64x96-2105271915-e100-bs256-lr0003-rs42.pth
100%|█████████████████████████████████████████████████████████████| 81.3M/81.3M [00:00<00:00, 115MB/s]
INFO:s3prl.util.download:Using URL's local file: /home/bagus/.cache/s3prl/download/b1ba7c8535b821757435847b42f913e2e93ce1c33622b7b6908da9265ceece97.resnetish34_BYOLAs64x96-2105271915-e100-bs256-lr0003-rs42.pth
Traceback (most recent call last):
  File "run_downstream.py", line 218, in <module>
    main()
  File "run_downstream.py", line 213, in main
    runner = Runner(args, config)
  File "/home/bagus/github/s3prl-ser/s3prl/downstream/runner.py", line 93, in __init__
    self.upstream = self._get_upstream()
  File "/home/bagus/github/s3prl-ser/s3prl/downstream/runner.py", line 149, in _get_upstream
    model = Upstream(
  File "/home/bagus/github/s3prl-ser/s3prl/upstream/byol_s/hubconf.py", line 30, in byol_s_resnetish34
    return _UpstreamExpert(**kwds)
TypeError: __init__() got an unexpected keyword argument 'model_config'
(.env) bagus@m049:s3prl$ 
```

Since  BYOL-S is one of the strongest submissions of the HEAR NeurIPS 2021, it is worth to try this upstream, particularly on paralinguistic tasks.

**Comment by popen8526** [comment]
## Step-1
Modify the code in `/s3prl/s3prl/upstream/byol_s/expert.py`, add the code which is marked as `# new edited`.
```
class UpstreamExpert(nn.Module):
    def __init__(
        self,
        ckpt: str = None,
        model_name: str = None,
        window_secs: float = 1,
        hop_secs: float = 0.05,
        model_config: str = None, # new edited
    ):
        super().__init__()
        self.model = serab.load_model(ckpt, model_name)
        self.frame_duration = window_secs * 1000
        self.hop_size = hop_secs * 1000
        self.model_config = model_config # new edited

```

## Step-2
Create new file `config.yaml` in `/s3prl/s3prl/upstream/byol_s/serab_byols`, and you can modify the parameter yourself.
```
# Unit duration in seconds for one audio segment.
unit_sec: 0.95
# FFT parameters.
sample_rate: 16000
n_fft: 1024
win_length: 400
hop_length: 160
n_mels: 64
f_min: 60
f_max: 7800
# Dimensions of feature representations.
feature_d: 2048
# BYOL parameters.
use_post_norm: True
proj_size: 256
proj_dim: 4096
ema_decay: 0.99
# Training parameters.
seed: 42
bs: 128
lr: 0.0003
epochs: 100
gpus: 2

# Weight pathname for resuming training.
resume:
# Shape of log-mel spectrogram [F, T].
shape: [64, 96]
# Folder to store trained weight files.
checkpoint_folder: checkpoints

# SST/ViT parameters
patch_shape: [64, 8]
num_heads: 8

# CvT parameters:
depths: [1, 1, 1]
embed_dims: [64, 256, 512]
mlp_mults: [4, 4, 4]
cvt_pool: mean+max
```
I'll make a pull request later.
@dlion168
