### ISSUE TITLE
RuntimeError: Tensors must be CUDA and dense

### ISSUE THREAD

**Issue by shanguanma** [s3prl/s3prl#478]
# Bug report

**Describe the bug**
A complete training loop and then evaluation, and finally the following error occurs
```
Traceback (most recent call last):
  File "/workspace2/maduo/s3prl/s3prl/run_downstream.py", line 229, in <module>
    main()
  File "/workspace2/maduo/s3prl/s3prl/run_downstream.py", line 225, in main
    eval(f'runner.{args.mode}')()
  File "/workspace2/maduo/s3prl/s3prl/downstream/runner.py", line 300, in train
    loss = self.downstream.model(
  File "/home/maduo/miniconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/maduo/miniconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1148, in forward
    self._sync_buffers()
  File "/home/maduo/miniconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1748, in _sync_buffers
    self._sync_module_buffers(authoritative_rank)
  File "/home/maduo/miniconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1752, in _sync_module_buffers
    self._default_broadcast_coalesced(
  File "/home/maduo/miniconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1775, in _default_broadcast_coalesced
    self._distributed_broadcast_coalesced(
  File "/home/maduo/miniconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1689, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(
RuntimeError: Tensors must be CUDA and dense
^Moverall:  10%|█         | 20000/200000 [29:41<4:27:09, 11.23it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2268002) of binary: /home/maduo/miniconda3/envs/fairseq_speechtext/bin/python
ome/maduo/miniconda3/envs/fairseq_speechtext/bin/python
Traceback (most recent call last):
  File "/home/maduo/miniconda3/envs/fairseq_speechtext/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/maduo/miniconda3/envs/fairseq_speechtext/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/maduo/miniconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/maduo/miniconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/maduo/miniconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/maduo/miniconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/maduo/miniconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/maduo/miniconda3/envs/fairseq_speechtext/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
s3prl/s3prl/run_downstream.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-24_17:16:50
  host      : lthpc-SYS-4029GP-TRT-BA001
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2268002)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
                                                                                         

```

**Environment**
List your **OS, Python, and PyTorch, and S3PRL** versions
```
>>> import s3prl
>>> s3prl.__version__
'0.4.10'
>>> import torch
>>> torch.__version__
'2.0.0'
```
Could you help me ? @hikushalhere

**Comment by shanguanma** [comment]
running command is as follows:
```
exp_dir=exp/downstream_task/downstream_task_ic_test_small_imls_ssl ## output 
   pretrain_model=$exp_dir/checkpoint_last.pt
   num_gpus=1
   downstream_task_config=s3prl/s3prl/downstream/fluent_commands/config.yaml
   CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --use_env \
          --nproc_per_node $num_gpus \
          s3prl/s3prl/run_downstream.py\
           -m train \
           -u imls_ssl_local\
           -k $pretrain_model\
           -d fluent_commands\
           --config $downstream_task_config\
           -o config.runner.gradient_accumulate_steps=4\
           --auto_resume \
           --expdir $exp_dir

```

**Comment by shanguanma** [comment]
My solution is that 
 `https://github.com/s3prl/s3prl/blob/main/s3prl/downstream/runner.py#L479`  is modified by `entry.model.train().to(self.args.device)`

**Comment by leo19941227** [comment]
Thanks for the suggestion! I am adding this fix
