### ISSUE TITLE
Asking for how to use pretrained weight of Hugging Face models in downstream tasks.

### ISSUE THREAD

**Issue by oohara1202** [s3prl/s3prl#510]
Hi.

I'm currently trying to train downstream of emotion recognition and use pretrained weight of [japanese HuBERT model](https://huggingface.co/rinna/japanese-hubert-base) by Hugging Face.

I used the following command but training don't started.

```
python3 run_downstream.py -n ExpName -m train -u hf_hubert_custom -d emotion -k rinna/japanese-hubert-base  -c downstream/emotion/config.yaml -o "config.downstream_expert.datarc.test_fold='fold1'"
```

```
python3 run_downstream.py -n ExpName -m train -u hf_hubert_custom -d emotion -k rinna/japanese-hubert-base -g rinna/japanese-hubert-base/main/config.json -c downstream/emotion/config.yaml -o "config.downstream_expert.datarc.test_fold='fold1'"
ESPnet is not installed, cannot use espnet_hubert upstream
[Runner] - Start a new experiment
[Override] - config.downstream_expert.datarc.test_fold = fold1
Traceback (most recent call last):
  File "/home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/rinna/japanese-hubert-base/resolve/main/preprocessor_config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages/transformers/utils/hub.py", line 429, in cached_file
    resolved_file = hf_hub_download(
  File "/home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1232, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1608, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 271, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-652e1c79-0f525dcc665d0a8a3f1264b0;f2c8193c-818a-4ca7-bca3-799912b2cf4d)

Entry Not Found for url: https://huggingface.co/rinna/japanese-hubert-base/resolve/main/preprocessor_config.json.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/abelab4/s_koha/s3prl/s3prl/run_downstream.py", line 219, in <module>
    main()
  File "/work/abelab4/s_koha/s3prl/s3prl/run_downstream.py", line 214, in main
    runner = Runner(args, config)
  File "/home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages/s3prl/downstream/runner.py", line 93, in __init__
    self.upstream = self._get_upstream()
  File "/home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages/s3prl/downstream/runner.py", line 149, in _get_upstream
    model = Upstream(
  File "/home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages/s3prl/upstream/hf_hubert/hubconf.py", line 5, in hf_hubert_custom
    return _UpstreamExpert(ckpt, *args, **kwargs)
  File "/home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages/s3prl/upstream/hf_hubert/expert.py", line 15, in __init__
    self.extracter = Wav2Vec2FeatureExtractor.from_pretrained(ckpt)
  File "/home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages/transformers/feature_extraction_utils.py", line 365, in from_pretrained
    feature_extractor_dict, kwargs = cls.get_feature_extractor_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages/transformers/feature_extraction_utils.py", line 488, in get_feature_extractor_dict
    resolved_feature_extractor_file = cached_file(
  File "/home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages/transformers/utils/hub.py", line 480, in cached_file
    raise EnvironmentError(
OSError: rinna/japanese-hubert-base does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co/rinna/japanese-hubert-base/main' for available files.
```

Please tell me right commands.

**Comment by leo19941227** [comment]
Hi, you should use  `-u hf_hubert_custom` with `-k rinna/japanese-hubert-base` as documented [here](https://s3prl.github.io/s3prl/tutorial/upstream_collection.html#hubert)

**Comment by oohara1202** [comment]
Thank you for your response!
However, I'm sorry, but pretrained weights are still not available...
I think the top command of this issue includes `-u hf_hubert_custom` with `-k rinna/japanese-hubert-base`, and I encountered  above error.

**Comment by leo19941227** [comment]
Weird. Let me check it.

**Comment by leo19941227** [comment]
Hi,

This is because the model `rinna/japanese-hubert-base` on HF only defines the model weights but without a corresponding feature extractor on HF. However, I believe we can faithfully use the default feature extractor of the original HuBERT base as an alternative, and the latest commit reflects this degenerating behaveior hence I believe the command you used can work now. Feel free the re-open the issue if the commit does not fix your issue.

**Comment by oohara1202** [comment]
Thank you for your patches.

However, dispate applying the latest commit, the problem remains...
 I'm encountering the same error...

By the way, my `transformers` version  (installed via pip) is 4.34.0.

**Comment by oohara1202** [comment]
Sorry.

Above comment is wrong.
I succeeded to train using the HF model!

In my s3prl environment, `Runner`  imported from  `s3prl.downstream.runner import Runner` (line 14) in `s3prl/run_downstream.py` is part of s3prl pip-packege, so I failed because pip-packege was not up-to-date.

Thank you for your fix!

**Comment by leo19941227** [comment]
Cool!
