### ISSUE TITLE
An error occurrs when adding new downstream tasks.

### ISSUE THREAD

**Issue by oohara1202** [s3prl/s3prl#511]
Hi.

I'm currently trying to add new downstream tasks.

According to [this reference](https://github.com/s3prl/s3prl/tree/main/s3prl/downstream#add-new-downstream-tasks), I made a new folder under `s3prl/downstream`.
```
$ cp -r s3prl/downstream/emotion/ s3prl/downstream/emotion_new
```

Then, I used the following command to start traning in the new folder but the training failed.
```
$ python3 run_downstream.py -n ExpName -m train -u hubert -d emotion_new -c downstream/emotion_new/config.yaml
```

```
$ python3 run_downstream.py -n ExpName -m train -u hubert -d emotion_new -c downstream/emotion_new/config
.yaml
ESPnet is not installed, cannot use espnet_hubert upstream
[Runner] - Start a new experiment
INFO:s3prl.util.download:Requesting URL: https://huggingface.co/s3prl/converted_ckpts/resolve/main/hubert_base_ls960.pt
INFO:s3prl.util.download:Using URL's local file: /home/abelab/s_koha/.cache/s3prl/download/cc1d9e25da3db01e710fe51bbcc725322be55e3d6eebc947f0aa4743e81bfc34.hubert_base_ls960.pt
INFO:s3prl.upstream.hubert.hubert_model:HubertModel Config: HubertConfig(label_rate=50.0, extractor_mode='default', encoder_layers=12, encoder_embed_dim=768, encoder_ffn_embed_dim=3072, encoder_attention_heads=12, activation_fn='gelu', layer_type='transformer', dropout=0.1, attention_dropout=0.1, activation_dropout=0.0, encoder_layerdrop=0.05, dropout_input=0.1, dropout_features=0.1, final_dim=256, untie_final_proj=False, layer_norm_first=False, conv_feature_layers='[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', conv_bias=False, logit_temp=0.1, target_glu=False, feature_grad_mult=0.1, mask_length=10, mask_prob=0.8, mask_selection='static', mask_other=0.0, no_mask_overlap=False, mask_min_space=1, mask_channel_length=10, mask_channel_prob=0.0, mask_channel_selection='static', mask_channel_other=0.0, no_mask_channel_overlap=False, mask_channel_min_space=1, conv_pos=128, conv_pos_groups=16, latent_temp=[2.0, 0.5, 0.999995], skip_masked=False, skip_nomask=False, checkpoint_activations=False, required_seq_len_multiple=2, depthwise_conv_kernel_size=31, attn_type='', pos_enc_type='abs', fp16=True)
[Featurizer] - Take a list of 13 features and weighted sum them.
[Featurizer] - The selected feature hidden_states's downsample rate is 320
Traceback (most recent call last):
  File "/work/abelab4/s_koha/s3prl/s3prl/run_downstream.py", line 219, in <module>
    main()
  File "/work/abelab4/s_koha/s3prl/s3prl/run_downstream.py", line 214, in main
    runner = Runner(args, config)
  File "/home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages/s3prl/downstream/runner.py", line 95, in __init__
    self.downstream = self._get_downstream()
  File "/home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages/s3prl/downstream/runner.py", line 184, in _get_downstream
    expert = importlib.import_module(f"s3prl.downstream.{self.args.downstream}.expert")
  File "/home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 's3prl.downstream.emotion_new'
```

By the way, my s3prl environment is FULL and EDITABLE installation (I used `pip install ".[all]"`), and I can train an already implemented task (emotion recognition on IEMOCAP) using bellow command:
```
$ python3 run_downstream.py -n ExpName -m train -u hubert -d emotion -c downstream/emotion/config.yaml  # ok
```

**Comment by leo19941227** [comment]
Hi, you can try to copy the entire `downstream/example` and rename it as `emotion_new`.
Then, check whether `python3 run_downstream.py -u hubert -d emotion_new -n test` can run.
If it works, you can develop your new downstream tasks within this folder.
For your current situation, I would suspect that you might forget to add the `__init__.py` inside your new downstream folder which is necessary for the folder to be considered as a package.

**Comment by oohara1202** [comment]
I tried to copy the entire `downstream/example` and rename it(the folder includes `__init__.py.).`
However, the same error occurred when I ran `python3 run_downstream.py -u hubert -d emotion_new -n test -m train` (Adding to the "mode" option) ...

Is it relevant that `Runner`, imported from `s3prl.downstream.runner import Runner` (line 214) in `s3prl/run_downstream.py` is part of `s3prl` pip-packege?
Also, wll my installation be correct? I used `pip install ".[all]"` to install EDITABLE s3prl.

**Comment by leo19941227** [comment]
Hi, can you paste the output of the following command?
```
pip show s3prl
```

**Comment by oohara1202** [comment]
Thank you for your response.
This is the output:
```
$ pip show s3prl
Name: s3prl
Version: 0.4.11
Summary: Self-Supervised Speech Pre-training and Representation Learning Toolkit
Home-page: https://github.com/s3prl/s3prl
Author: Shu-wen (Leo) Yang, Andy T. Liu (Ting-Wei Liu), and the S3PRL Team
Author-email: leo19941227@gmail.com, liuandyt@gmail.com
License: Apache Software License
Location: /home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages
Requires: filelock, numpy, omegaconf, protobuf, PyYAML, requests, setuptools, torch, torchaudio, tqdm, transformers
Required-by:
```

**Comment by leo19941227** [comment]
Hi,

`Location: /home/abelab/s_koha/miniconda3/envs/superb/lib/python3.9/site-packages`
This line indicates that you are actually using a non-editable-installed version of s3prl.
That version of s3prl is under the site packages folder and is not aware of your local modification 
Please uninstall the current s3prl and rerun the `pip install -e ".[all]"`

**Comment by oohara1202** [comment]
Thanks!
The location changed to my local.

Thank you very much for your response to my elementary mistake.

**Comment by leo19941227** [comment]
Cool
