### ISSUE TITLE
Requesting to add CLSRIL-23 pretrained model as new upstream

### ISSUE THREAD

**Issue by mukherjeesougata** [s3prl/s3prl#533]
I want to use wav2vec2 [wav2vec2-pretrained-clsril-23-10k](https://huggingface.co/Harveenchadha/wav2vec2-pretrained-clsril-23-10k)/[CLSRIL-23](https://storage.googleapis.com/vakyansh-open-models/pretrained_models/clsril-23/CLSRIL-23.pt) pretrained model features for training CTC/Attention network without language model for ASR task using [ESPnet](https://github.com/espnet/espnet) toolkit. I am using [this](https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/asr.sh) script and [config](https://github.com/espnet/espnet/blob/8a8709e6579a593eef2e98433a7e69a6ae1c828f/egs2/fleurs/asr1/conf/tuning/train_asr_conformer_scctc.yaml) file for that. But, [wav2vec2-pretrained-clsril-23-10k](https://huggingface.co/Harveenchadha/wav2vec2-pretrained-clsril-23-10k) is not enlisted under converted_ckpts or upstream [list](https://huggingface.co/s3prl/converted_ckpts/tree/main). So,I am requesting  to add [this](https://huggingface.co/s3prl/converted_ckpts/tree/main) as S3PRL upstream.

**Comment by leo19941227** [comment]
Hi @mukherjeesougata ,

Despite we support to load huggingface models, but my initial try find that we can not successfully load this model.
I am working on this and will get back to you later.

**Comment by leo19941227** [comment]
Hi @mukherjeesougata ,

I think I fix the issue in the latest `s3prl>=v0.4.15`, please upgrade the S3PRL version and try using the following params for the config file in ESPNet:

```python
upstream: hf_wav2vec2_custom
path_or_url: Harveenchadha/wav2vec2-pretrained-clsril-23-10k
```

**Comment by mukherjeesougata** [comment]
I am using ```s3prl>=v0.4.15``` and have also modified the config file as:
```
upstream: hf_wav2vec2_custom
path_or_url: Harveenchadha/wav2vec2-pretrained-clsril-23-10k
``` 
But still it is showing the following error:-
```
Traceback (most recent call last):
  File "/home/sougata/anaconda3/envs/espnet_latest/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sougata/anaconda3/envs/espnet_latest/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sougata/espnet_latest/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/home/sougata/espnet_latest/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/home/sougata/espnet_latest/espnet/espnet2/tasks/abs_task.py", line 1154, in main
    cls.main_worker(args)
  File "/home/sougata/espnet_latest/espnet/espnet2/tasks/abs_task.py", line 1471, in main_worker
    cls.trainer.run(
  File "/home/sougata/espnet_latest/espnet/espnet2/train/trainer.py", line 317, in run
    all_steps_are_invalid = cls.train_one_epoch(
  File "/home/sougata/espnet_latest/espnet/espnet2/train/trainer.py", line 614, in train_one_epoch
    retval = model(**batch)
  File "/home/sougata/anaconda3/envs/espnet_latest/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sougata/anaconda3/envs/espnet_latest/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sougata/espnet_latest/espnet/espnet2/asr/espnet_model.py", line 237, in forward
    encoder_out, encoder_out_lens = self.encode(speech, speech_lengths)
  File "/home/sougata/espnet_latest/espnet/espnet2/asr/espnet_model.py", line 390, in encode
    feats, feats_lengths = self.preencoder(feats, feats_lengths)
  File "/home/sougata/anaconda3/envs/espnet_latest/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sougata/anaconda3/envs/espnet_latest/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sougata/espnet_latest/espnet/espnet2/asr/preencoder/linear.py", line 31, in forward
    output = self.linear_out(self.dropout(input))
  File "/home/sougata/anaconda3/envs/espnet_latest/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sougata/anaconda3/envs/espnet_latest/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sougata/anaconda3/envs/espnet_latest/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (12152x768 and 1024x80)
```

**Comment by leo19941227** [comment]
Change this hyper to 768:

https://github.com/espnet/espnet/blob/8a8709e6579a593eef2e98433a7e69a6ae1c828f/egs2/fleurs/asr1/conf/tuning/train_asr_conformer_scctc.yaml#L88

**Comment by mukherjeesougata** [comment]
Yeah, it is a base model. I have overlooked that. It was a silly mistake from my side. Now, it seems it is working, at least the 1st epoch of training has been completed without any error.

**Comment by leo19941227** [comment]
Cool!
