### ISSUE TITLE
Error when using GPU based mockingjay Upstream_local model

### ISSUE THREAD

**Issue by Vanka0051** [s3prl/s3prl#91]
torch==1.5.0, torchaudio==0.5.0
using upstream/mockingjay/example_extracter.py to extract features from my own mockingjay model
got Error in forward function when extract fbank features from wav using GPU. 

`Traceback (most recent call last):
  File "test.py", line 38, in <module>
    reps = model_local(example_wavs)
  File "/home/yckj3408/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yckj3408/speech_representation/s3prl-master/upstream/mockingjay/expert.py", line 63, in forward
    features = self.transformer(wavs) # (batch_size, extracted_seqlen, feature_dim)
  File "/home/yckj3408/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yckj3408/speech_representation/s3prl-master/upstream/mockingjay/builder.py", line 272, in forward
    x = [self.extracter(x_i) for x_i in x]
  File "/home/yckj3408/speech_representation/s3prl-master/upstream/mockingjay/builder.py", line 272, in <listcomp>
    x = [self.extracter(x_i) for x_i in x]
  File "/home/yckj3408/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yckj3408/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/yckj3408/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yckj3408/speech_representation/s3prl-master/upstream/baseline/extracter.py", line 37, in forward
    **self.kwargs
  File "/home/yckj3408/anaconda3/lib/python3.7/site-packages/torchaudio/compliance/kaldi.py", line 554, in fbank
    snip_edges, raw_energy, energy_floor, dither, remove_dc_offset, preemphasis_coefficient)
  File "/home/yckj3408/anaconda3/lib/python3.7/site-packages/torchaudio/compliance/kaldi.py", line 180, in _get_window
    signal_log_energy = _get_log_energy(strided_input, EPSILON, energy_floor)  # size (m)
  File "/home/yckj3408/anaconda3/lib/python3.7/site-packages/torchaudio/compliance/kaldi.py", line 113, in _get_log_energy
    log_energy = torch.max(strided_input.pow(2).sum(1), epsilon).log()  # size (m)
RuntimeError: iter.device(arg).is_cuda() INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/native/cuda/Loops.cuh:56, please report a bug to PyTorch.`

it seems that for torch==1.5.0 and torchaudio==0.5.0, torchaudio.compliance.kaldi.fbank dose not support GPU however I set wav tensor into "cuda" device and cause the error.
Solving the problem by changing torch==1.7.0, torchaudio==0.7.0. However, torch==1.5.0 and torchaudio==0.5.0 satisfy the requirements.txt provided
Besides torch==1.5.0 does not have `torch.hub.get_dir` function used in utility/download.py

Maybe modify the requirements.txt?

**Comment by leo19941227** [comment]
Thanks for pointing out. I will fix this later.

**Comment by leo19941227** [comment]
I found that we have already fix the torch version to 1.7.0 in the latest `master`. So I think this issue is resolved.
